import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertCircle, CheckCircle2, ExternalLink, FileText, RefreshCw, Search, X } from 'lucide-react';
import PPDBModal from './PPDBModal';
import PPDBTable from './PPDBTable';
import { getPpdb, getPpdbDocumentUrl, updatePpdbStatus } from '../../../services/ppdbService';

const statusLabels = { menunggu: 'Menunggu', diproses: 'Diproses', diterima: 'Diterima', ditolak: 'Ditolak' };
const statusClasses = { menunggu: 'bg-amber-100 text-amber-700', diproses: 'bg-blue-100 text-blue-700', diterima: 'bg-green-100 text-green-700', ditolak: 'bg-red-100 text-red-700' };
const formatDate = (value) => value ? new Intl.DateTimeFormat('id-ID', { dateStyle: 'long' }).format(new Date(value)) : '-';
const formatDateTime = (value) => value ? new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '-';
const getErrorMessage = (error, fallback) => error?.code === '42501' ? 'Anda tidak memiliki izin untuk melakukan tindakan ini.' : error?.message || fallback;

const PPDBPage = () => {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [feedback, setFeedback] = useState(null); const [query, setQuery] = useState(''); const [statusFilter, setStatusFilter] = useState('all'); const [modal, setModal] = useState(null); const [status, setStatus] = useState('menunggu'); const [note, setNote] = useState(''); const [saving, setSaving] = useState(false); const [documentLoading, setDocumentLoading] = useState(false);

  const loadPpdb = useCallback(async () => { setLoading(true); setError(''); try { setItems(await getPpdb()); } catch (loadError) { setError(getErrorMessage(loadError, 'Data pendaftar gagal dimuat.')); } finally { setLoading(false); } }, []);
  useEffect(() => { // eslint-disable-next-line react-hooks/set-state-in-effect
    void loadPpdb();
  }, [loadPpdb]);
  useEffect(() => { if (!feedback) return undefined; const timer = window.setTimeout(() => setFeedback(null), 4000); return () => window.clearTimeout(timer); }, [feedback]);

  const filteredItems = useMemo(() => { const q = query.trim().toLowerCase(); return items.filter((item) => (statusFilter === 'all' || item.status === statusFilter) && (!q || [item.nama_lengkap, item.nisn, item.asal_sekolah, item.email].filter(Boolean).join(' ').toLowerCase().includes(q))); }, [items, query, statusFilter]);
  const openEdit = (item) => { setStatus(item.status); setNote(item.catatan_admin || ''); setModal({ type: 'edit', item }); };
  const closeModal = () => { if (!saving && !documentLoading) setModal(null); };
  const handleSave = async () => { setSaving(true); try { await updatePpdbStatus(modal.item.id, status, note); setModal(null); setFeedback({ type: 'success', message: 'Status dan catatan pendaftar berhasil diperbarui.' }); await loadPpdb(); } catch (saveError) { setFeedback({ type: 'error', message: getErrorMessage(saveError, 'Perubahan pendaftar gagal disimpan.') }); } finally { setSaving(false); } };
  const handleDocument = async () => { setDocumentLoading(true); try { const url = await getPpdbDocumentUrl(modal.item.dokumen_url); if (!url) throw new Error('Dokumen tidak tersedia.'); window.open(url, '_blank', 'noopener,noreferrer'); } catch (documentError) { setFeedback({ type: 'error', message: getErrorMessage(documentError, 'Dokumen gagal dibuka.') }); } finally { setDocumentLoading(false); } };

  return <section><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">Panel Admin</p><h1 className="mt-2 font-heading text-2xl font-extrabold text-dark-900 sm:text-3xl">Kelola PPDB</h1><p className="mt-2 text-sm text-dark-500">Tinjau pendaftar dan proses status pendaftaran siswa baru.</p></div></div>
    {feedback && <div className={`mt-5 flex items-start gap-3 rounded-lg border px-4 py-3 text-sm ${feedback.type === 'success' ? 'border-green-200 bg-green-50 text-green-700' : 'border-primary-200 bg-primary-50 text-primary-800'}`} role="status">{feedback.type === 'success' ? <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0" /> : <AlertCircle className="mt-0.5 h-4 w-4 shrink-0" />}<span className="flex-1">{feedback.message}</span><button type="button" onClick={() => setFeedback(null)} aria-label="Tutup notifikasi"><X className="h-4 w-4" /></button></div>}
    <div className="mt-6 flex flex-col gap-3 rounded-2xl border border-dark-100 bg-white p-4 shadow-card sm:flex-row sm:flex-wrap"><label className="relative min-w-0 flex-1"><span className="sr-only">Cari pendaftar</span><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-dark-400" /><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari nama, NISN, asal sekolah, atau email..." className="w-full rounded-lg border border-dark-200 py-2.5 pl-10 pr-3 text-sm outline-none placeholder:text-dark-400 focus:border-primary" /></label><select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)} className="rounded-lg border border-dark-200 px-3 py-2.5 text-sm text-dark-700 outline-none focus:border-primary" aria-label="Filter status PPDB"><option value="all">Semua Status</option>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><button type="button" onClick={loadPpdb} disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-lg border border-dark-200 px-3 py-2.5 text-xs font-bold text-dark-600 hover:border-primary hover:text-primary disabled:opacity-50" title="Muat ulang"><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} /><span className="sm:hidden">Muat ulang</span></button></div>
    <div className="mt-5">{loading ? <div className="rounded-2xl border border-dark-100 bg-white p-12 text-center text-sm text-dark-500 shadow-card">Memuat data pendaftar...</div> : error ? <div className="rounded-2xl border border-primary-200 bg-primary-50 p-8 text-center shadow-card"><AlertCircle className="mx-auto h-8 w-8 text-primary" /><p className="mt-3 text-sm font-semibold text-primary-800">{error}</p><button type="button" onClick={loadPpdb} className="mt-4 rounded-lg bg-primary px-4 py-2 text-xs font-bold text-white hover:bg-primary-800">Coba Lagi</button></div> : items.length === 0 ? <div className="rounded-2xl border border-dashed border-dark-300 bg-white p-12 text-center text-sm text-dark-500 shadow-card">Belum ada pendaftar PPDB.</div> : filteredItems.length === 0 ? <div className="rounded-2xl border border-dashed border-dark-300 bg-white p-12 text-center text-sm text-dark-500 shadow-card">Tidak ada pendaftar yang cocok dengan pencarian atau filter.</div> : <PPDBTable items={filteredItems} onDetail={(item) => setModal({ type: 'detail', item })} onEdit={openEdit} />}</div>
    {!loading && !error && items.length > 0 && <p className="mt-3 text-center text-xs text-dark-400">Menampilkan {filteredItems.length} dari {items.length} pendaftar</p>}
    {modal?.type === 'detail' && <PPDBModal title="Detail Pendaftar" onClose={closeModal}><div className="grid gap-4 text-sm sm:grid-cols-2"><div><p className="text-xs text-dark-400">Nama Lengkap</p><p className="mt-1 font-semibold text-dark-900">{modal.item.nama_lengkap}</p></div><div><p className="text-xs text-dark-400">NISN</p><p className="mt-1 text-dark-700">{modal.item.nisn || '-'}</p></div><div><p className="text-xs text-dark-400">Asal Sekolah</p><p className="mt-1 text-dark-700">{modal.item.asal_sekolah}</p></div><div><p className="text-xs text-dark-400">Tempat, Tanggal Lahir</p><p className="mt-1 text-dark-700">{[modal.item.tempat_lahir, formatDate(modal.item.tanggal_lahir)].filter(Boolean).join(', ') || '-'}</p></div><div><p className="text-xs text-dark-400">Jenis Kelamin</p><p className="mt-1 text-dark-700">{modal.item.jenis_kelamin || '-'}</p></div><div><p className="text-xs text-dark-400">Nomor HP</p><p className="mt-1 text-dark-700">{modal.item.no_hp || '-'}</p></div><div><p className="text-xs text-dark-400">Email</p><p className="mt-1 break-all text-dark-700">{modal.item.email || '-'}</p></div><div><p className="text-xs text-dark-400">Pilihan Jurusan</p><p className="mt-1 text-dark-700">{modal.item.pilihan_jurusan}</p></div><div className="sm:col-span-2"><p className="text-xs text-dark-400">Alamat</p><p className="mt-1 whitespace-pre-wrap text-dark-700">{modal.item.alamat || '-'}</p></div><div><p className="text-xs text-dark-400">Status</p><span className={`mt-1 inline-flex rounded-full px-2.5 py-1 text-[10px] font-bold ${statusClasses[modal.item.status]}`}>{statusLabels[modal.item.status]}</span></div><div><p className="text-xs text-dark-400">Tanggal Daftar</p><p className="mt-1 text-dark-700">{formatDateTime(modal.item.created_at)}</p></div><div className="sm:col-span-2"><p className="text-xs text-dark-400">Catatan Admin</p><p className="mt-1 whitespace-pre-wrap text-dark-700">{modal.item.catatan_admin || '-'}</p></div></div>{modal.item.dokumen_url && <button type="button" onClick={handleDocument} disabled={documentLoading} className="mt-6 inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-xs font-bold text-white hover:bg-primary-800 disabled:opacity-60"><FileText className="h-4 w-4" />{documentLoading ? 'Membuka dokumen...' : 'Lihat Dokumen'}<ExternalLink className="h-3.5 w-3.5" /></button>}</PPDBModal>}
    {modal?.type === 'edit' && <PPDBModal title="Perbarui Status Pendaftar" onClose={closeModal}><p className="text-sm text-dark-600">{modal.item.nama_lengkap}</p><label className="mt-5 block"><span className="mb-1.5 block text-xs font-semibold text-dark-700">Status</span><select value={status} onChange={(event) => setStatus(event.target.value)} className="w-full rounded-lg border border-dark-200 px-3 py-2.5 text-sm outline-none focus:border-primary"><option value="menunggu">Menunggu</option><option value="diproses">Diproses</option><option value="diterima">Diterima</option><option value="ditolak">Ditolak</option></select></label><label className="mt-4 block"><span className="mb-1.5 block text-xs font-semibold text-dark-700">Catatan Admin</span><textarea value={note} onChange={(event) => setNote(event.target.value)} rows="5" className="w-full resize-y rounded-lg border border-dark-200 px-3 py-2.5 text-sm outline-none focus:border-primary" placeholder="Tambahkan catatan untuk pendaftar..." /></label><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={closeModal} disabled={saving} className="rounded-lg border border-dark-200 px-4 py-2.5 text-xs font-bold text-dark-600 hover:border-dark-400 disabled:opacity-50">Batal</button><button type="button" onClick={handleSave} disabled={saving} className="rounded-lg bg-primary px-4 py-2.5 text-xs font-bold text-white hover:bg-primary-800 disabled:opacity-60">{saving ? 'Menyimpan...' : 'Simpan Perubahan'}</button></div></PPDBModal>}
  </section>;
};

export default PPDBPage;

